sudo: required
services:
 - docker
	
	
before_install:
 - docker build -t dandocker1989/docker-tutorial-react -f Dockerfile.dev .
 
script:
 - docker run dandocker1989/docker-tutorial-react npm run test -- --coverage
  